#!/usr/bin/env bash

# Replace with your generated URL from README instructions.
SLACK_WEBHOOK_URL=https://hooks.slack.com/services/xxxxxxxxx/yyyyyyyyyy/zzzzzzzzzz

if [ -n "$TUPLE_HOOK_IS_SELF" ]; then
  MESSAGE="$TUPLE_HOOK_FULL_NAME joined the $TUPLE_HOOK_ROOM_NAME room"
  curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"$MESSAGE\"}" $SLACK_WEBHOOK_URL
fi
